import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function FAQ() {
  const faqs = [
    {
      question: "What is AI-powered content creation?",
      answer:
        "AI-powered content creation uses artificial intelligence to help generate, optimize, and enhance content, making it more effective for SEO, blogs, and e-commerce.",
    },
    {
      question: "How can AI improve my SEO?",
      answer:
        "AI analyzes data, keywords, and trends to optimize your content for search engines, improving your website's ranking and driving more traffic.",
    },
    {
      question: "Can I customize the content generated by the AI?",
      answer:
        "Yes, our platform allows you to customize AI-generated content to match your brand's voice and style while maintaining SEO best practices.",
    },
    {
      question: "Is it easy to integrate with my existing website?",
      answer:
        "Absolutely. Our AI content platform offers easy integration with most CMS and e-commerce platforms to streamline your workflow.",
    },
    {
      question: "How secure is my data?",
      answer:
        "We prioritize security, ensuring your data is encrypted and protected with industry-standard security protocols.",
    },
  ];
  return (
    <div className="w-full max-w-7xl mx-auto px-4 py-16" id="faq">
      <div className="mx-auto space-y-5 py-6 text-center">
        <h2 className="text-blue-600 font-mono text-[14px] font-medium tracking-tight">
          FAQs
        </h2>
        <h2 className="mx-auto mb-2 max-w-3xl text-balance text-[42px] font-medium leading-tight tracking-tighter">
          Frequently Asked Questions
        </h2>
      </div>
      <Accordion type="single" collapsible className="w-full space-y-4">
        {faqs.map((faq, index) => (
          <AccordionItem
            key={index}
            value={`item-${index}`}
            className="w-full p-3"
          >
            <AccordionTrigger className="text-start">
              {faq.question}
            </AccordionTrigger>
            <AccordionContent>{faq.answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}
